app_name: LL! SIF Private Server
server:
    powered_by: KLab Native APP Platform
    version_date: "20120129"
    version_number: 97.4.6
    version_up: "0"
log:
    log_dir: logs
    log_level: 5
    log_save: true
leveldb:
    data_path: ./data/honoka-chan.db
